version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3306" # El primer port es de tu equipo local, el segundo apunta a la imagen
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    container_name: centro_down_laravel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
